// ════════════════════════════════════════════════════════════
//  TRANSLATIONS — English / Turkish
// ════════════════════════════════════════════════════════════
window.TRANSLATIONS = {
  en: {
    langBtn: "TR",
    nav: { routing: "Routing", analytics: "Analytics", insights: "Insights", methodology: "Methodology" },
    brand: { sub: "Logistics Carbon Routing · Diploma Projesi" },
    catDesc: {
      "China Import":   "Inbound from Greater China to İzmir.",
      "Italy Export":   "Aliağa / ESBAŞ outbound to Italian hubs.",
      "Germany Export": "Outbound to German manufacturing centres.",
      "Italy Import":   "Italian origins inbound to ESBAŞ.",
    },
    routing: {
      step1: "Step 01", tradeLane: "Trade lane",
      step2: "Step 02", routeOption: "Route option",
      step3: "Step 03", container: "Container",
      computing: "Calculating…", compute: "Compute route",
      method: "Hand-verified maritime corridors at 90 km steps, road at 60 km. Emission factors per EcoTransit WTW (ISO 14083).",
      geoPreview: "Geospatial preview",
      selectRoute: "Select a route to begin",
      loadingMap: "Loading cartography…",
      configureRoute: "Configure a route to see analytics",
      pickLane: "Pick a trade lane on the left, then click",
      risk: "risk",
    },
    kpi: {
      totalDist: "Total distance", allLegs: "across all legs",
      totalCO2: "Total CO₂e", tonnes: "tonnes", kgTotal: "kg total",
      intensity: "Emission intensity",
      payload: "Container payload", avgPayload: "avg payload",
    },
    emissions: {
      eyebrow: "02 · Emissions", title: "Well-to-wheel carbon footprint",
      preCarriage: "Pre-carriage", pickupPOL: "Pickup → POL",
      mainTransport: "Main transport",
      inlandMainline: "Inland mainline",
      onCarriage: "On-carriage", podDelivery: "POD → Delivery",
      road: "road",
      containerSensitivity: "Container sensitivity",
      selected: "selected",
    },
    route: {
      eyebrow: "03 · Route legs", title: "Journey breakdown",
    },
    risk: {
      eyebrow: "04 · Risk", title: "Geopolitical exposure",
      level: { Low: "Low", Medium: "Medium", High: "High" },
    },
    insight: {
      eyebrow: "05 · Insight",
    },
    analytics: {
      eyebrow: "Module 02", title: "Route Analytics",
      sub: "Compare every route in a trade lane side-by-side. See which path delivers the lowest carbon footprint, shortest distance, and lowest geopolitical exposure.",
      tradeLane: "Trade lane", container: "Container",
      lowestCO2: "Lowest CO₂e", shortestDist: "Shortest distance", lowestRisk: "Lowest risk exposure",
      colRoute: "Route", colModes: "Modes", colDist: "Distance", colCO2: "CO₂ emissions", colRisk: "Risk", colIntensity: "Intensity",
      best: "Best",
      s1eyebrow: "01 · Side-by-side", routeComparison: "Route comparison",
      options: "options",
      s2eyebrow: "02 · Emission anatomy", emTitle: "Where does the CO₂ come from?",
      emSub: "Stacked by segment · pre-carriage, main transport, on-carriage",
      preCarriage: "Pre-carriage (road)", mainTransport: "Main transport", onCarriage: "On-carriage (road)",
      s3eyebrow: "03 · Trade-off", tradeoffTitle: "Distance vs emissions",
      tradeoffSub: "Bottom-left quadrant = the sweet spot",
      sweetSpot: "SWEET SPOT",
    },
    insights: {
      eyebrow: "Module 03 · Industry insights",
      title: "The decarbonisation decade",
      titleEm: "for automotive logistics",
      sub: "Between <b>2024 and 2035</b> the European automotive supply chain will pass through six overlapping regulatory regimes — CSRD, CBAM, Euro 7, ETS2, FuelEU Maritime and the 2035 ICE ban. For a Türkiye–EU lane operator like Eldor, each one rewires the cost of carbon in a different way. This page sketches the landscape and ties it back to the routes you can model in the tool.",
      annualStat: (n) => `Annual emissions at ${n.toLocaleString()} TEU/yr · fleet-avg lane`,
      etsStat: (p) => `ETS-equivalent exposure at €${p}/t (illustrative)`,
      railStat: "Achievable cut by shifting long-haul road to RoRo + rail",
      s1eyebrow: "01 · Baseline", s1title: "Carbon intensity by transport mode",
      s1sub: "EcoTransit / GLEC well-to-wheel emission factors · g CO₂e per tonne-kilometre",
      s2eyebrow: "02 · Timeline", s2title: "Regulatory horizon · 2024 → 2050",
      s3eyebrow: "03 · Best-in-class", s3title: "Lowest-emission route per trade lane",
      s4eyebrow: "04 · Modal shift", s4title: "What if Eldor shifted 40% of road tonnage to rail/RoRo?",
    },
    methodology: {
      eyebrow: "Module 04", title: "Methodology — EcoTransit WTW",
      sub: "Every kilogram of CO₂ in this dashboard is calculated using the EcoTransit emission model, aligned with ISO 14083:2023 — the international standard for quantifying greenhouse gas emissions from transport chains.",
      steps: [
        { n: "01", t: "Identify segments",   d: "Decompose route into pickup → POL → POD → delivery legs." },
        { n: "02", t: "Assign modes & EFs",  d: "Pull EcoTransit emission factor per mode (g CO₂e per t-km)." },
        { n: "03", t: "Apply payload",       d: "Multiply by container average payload (ISO standard)." },
        { n: "04", t: "Sum & report",        d: "Aggregate WTW (well-to-wheel) emissions across all legs." },
      ],
      formulaEyebrow: "The formula", formulaTitle: "Core calculation per segment",
      efEyebrow: "Emission factors", efTitle: "Per transport mode",
      efSub: "g CO₂e per tonne-kilometre · WTW basis",
      efNotes: {
        sea:     "Lowest intensity; ideal for long-haul bulk.",
        rail:    "Electric traction; low-carbon for inland.",
        railBRI: "Higher EF — diesel + gauge breaks.",
        roro:    "Roll-on/roll-off · medium intensity.",
        road:    "Highest intensity; door-to-door flex.",
      },
      contEyebrow: "Container payloads", contTitle: "Average cargo weight",
      contSub: "ISO container specs · midpoint of operational range",
      exEyebrow: "Worked example", exTitle: "Shanghai → ESBAŞ via Suez · 40FT",
      exSub: "Every number in this dashboard is built from operations like this",
      preCarriage: "Pre-carriage", mainTransport: "Main transport", onCarriage: "On-carriage",
      totalCO2: "TOTAL CO₂e",
      wtwEyebrow: "WTW vs TTW", wtwTitle: "Why well-to-wheel matters",
      ttwTitle: "Tank-to-wheel (TTW)",
      ttwDesc:  "Tailpipe emissions only — what comes out the exhaust during transport.",
      ttwCov:   "Covers: combustion only",
      wtwTitle2: "Well-to-wheel (WTW)",
      wtwDesc2: "Full lifecycle: fuel extraction, refining, distribution, AND combustion. Always 20–30% higher than TTW.",
      wtwCov2:  "Covers: upstream + tailpipe",
      wtwArrow: "→ extends to →",
      stdEyebrow: "Standards & sources", stdTitle: "Why these numbers can be trusted",
    },
    footer: {
      dataset: "Dataset",    datasetVal: "4 categories · maritime + road + rail",
      emission: "Emission model", emissionVal: "EcoTransit WTW · ISO 14083 compliant",
      carto: "Cartography",  cartoVal: "OpenStreetMap · CARTO basemap",
      copy: "© 2026 Eldor Trade Lanes — Academic build",
    },
    routeLabels: {},   // English labels come from engine.js directly
    routeDescs:  {},
  },

  tr: {
    langBtn: "EN",
    nav: { routing: "Rota", analytics: "Analiz", insights: "Görüşler", methodology: "Metodoloji" },
    brand: { sub: "Lojistik Karbon Yönlendirme · Diploma Projesi" },
    catDesc: {
      "China Import":   "Büyük Çin'den İzmir'e gelen yükler.",
      "Italy Export":   "Aliağa / ESBAŞ'tan İtalya merkezlerine giden yükler.",
      "Germany Export": "Almanya üretim merkezlerine giden yükler.",
      "Italy Import":   "İtalya'dan ESBAŞ'a gelen yükler.",
    },
    routing: {
      step1: "Adım 01", tradeLane: "Ticaret Koridoru",
      step2: "Adım 02", routeOption: "Rota Seçeneği",
      step3: "Adım 03", container: "Konteyner",
      computing: "Hesaplanıyor…", compute: "Rotayı Hesapla",
      method: "El ile doğrulanmış deniz koridorları 90 km adımlarla, kara yolu 60 km. Emisyon faktörleri EcoTransit WTW (ISO 14083) esas alınarak.",
      geoPreview: "Coğrafi Ön İzleme",
      selectRoute: "Başlamak için bir rota seçin",
      loadingMap: "Harita yükleniyor…",
      configureRoute: "Analiz için bir rota yapılandırın",
      pickLane: "Soldan bir ticaret koridoru seçin, ardından tıklayın",
      risk: "risk",
    },
    kpi: {
      totalDist: "Toplam Mesafe", allLegs: "tüm ayaklar dahil",
      totalCO2: "Toplam CO₂e", tonnes: "ton", kgTotal: "kg toplam",
      intensity: "Emisyon Yoğunluğu",
      payload: "Konteyner Yükü", avgPayload: "ort. yük",
    },
    emissions: {
      eyebrow: "02 · Emisyonlar", title: "Kuyudan tekere karbon ayak izi",
      preCarriage: "Ön Taşıma", pickupPOL: "Teslim Alma → POL",
      mainTransport: "Ana Taşıma",
      inlandMainline: "İç Hat Ana Hattı",
      onCarriage: "Son Taşıma", podDelivery: "POD → Teslimat",
      road: "kara yolu",
      containerSensitivity: "Konteyner Duyarlılığı",
      selected: "seçili",
    },
    route: {
      eyebrow: "03 · Rota Ayakları", title: "Yolculuk dökümü",
    },
    risk: {
      eyebrow: "04 · Risk", title: "Jeopolitik maruziyet",
      level: { Low: "Düşük", Medium: "Orta", High: "Yüksek" },
    },
    insight: {
      eyebrow: "05 · Değerlendirme",
    },
    analytics: {
      eyebrow: "Modül 02", title: "Rota Analizi",
      sub: "Bir ticaret koridorundaki her rotayı yan yana karşılaştırın. En düşük karbon ayak izi, en kısa mesafe ve en düşük jeopolitik risk hangi güzergahta olduğunu görün.",
      tradeLane: "Ticaret Koridoru", container: "Konteyner",
      lowestCO2: "En Düşük CO₂e", shortestDist: "En Kısa Mesafe", lowestRisk: "En Düşük Risk",
      colRoute: "Rota", colModes: "Modlar", colDist: "Mesafe", colCO2: "CO₂ Emisyonları", colRisk: "Risk", colIntensity: "Yoğunluk",
      best: "En İyi",
      s1eyebrow: "01 · Yan Yana", routeComparison: "Rota Karşılaştırması",
      options: "seçenek",
      s2eyebrow: "02 · Emisyon Anatomisi", emTitle: "CO₂ nereden geliyor?",
      emSub: "Segmente göre yığılmış · ön taşıma, ana taşıma, son taşıma",
      preCarriage: "Ön Taşıma (kara)", mainTransport: "Ana Taşıma", onCarriage: "Son Taşıma (kara)",
      s3eyebrow: "03 · Denge", tradeoffTitle: "Mesafe - Emisyon Dengesi",
      tradeoffSub: "Sol alt köşe = ideal nokta",
      sweetSpot: "İDEAL NOKTA",
    },
    insights: {
      eyebrow: "Modül 03 · Sektör Görüşleri",
      title: "Dekarbonizasyon on yılı",
      titleEm: "otomotiv lojistiği için",
      sub: "<b>2024 ile 2035</b> arasında Avrupa otomotiv tedarik zinciri altı iç içe düzenleyici rejimden geçecek — CSRD, CBAM, Euro 7, ETS2, FuelEU Maritime ve 2035 ICE yasağı. Eldor gibi bir Türkiye–AB koridor operatörü için her biri karbon maliyetini farklı biçimde yeniden yapılandırıyor. Bu sayfa bu ortamı özetliyor ve araçta modelleyebileceğiniz rotalara bağlıyor.",
      annualStat: (n) => `${n.toLocaleString()} TEU/yıl'da yıllık emisyonlar · filo-ort. hat`,
      etsStat: (p) => `€${p}/t'de ETS-eşdeğer maruziyet (gösterge amaçlı)`,
      railStat: "Uzun mesafeli karayolunu RoRo + demiryoluna kaydırarak elde edilebilecek azalma",
      s1eyebrow: "01 · Temel", s1title: "Taşıma moduna göre karbon yoğunluğu",
      s1sub: "EcoTransit / GLEC kuyudan tekere emisyon faktörleri · g CO₂e / tonne-kilometre",
      s2eyebrow: "02 · Zaman Çizelgesi", s2title: "Düzenleyici ufuk · 2024 → 2050",
      s3eyebrow: "03 · En İyi Sınıf", s3title: "Ticaret koridoru başına en düşük emisyonlu rota",
      s4eyebrow: "04 · Modal Kayma", s4title: "Eldor karayolu tonajının %40'ını demiryoluna/RoRo'ya kaydırsaydı?",
    },
    methodology: {
      eyebrow: "Modül 04", title: "Metodoloji — EcoTransit WTW",
      sub: "Bu panodaki her kilogram CO₂, ISO 14083:2023 ile uyumlu EcoTransit emisyon modeli kullanılarak hesaplanmıştır — bu standart, taşımacılık zincirlerinden kaynaklanan sera gazı emisyonlarını ölçmek için uluslararası referanstır.",
      steps: [
        { n: "01", t: "Segmentleri Belirle",  d: "Rotayı teslim alma → POL → POD → teslimat ayaklarına böl." },
        { n: "02", t: "Mod ve EF Ata",        d: "Her taşıma modu için EcoTransit emisyon faktörünü belirle (g CO₂e/t-km)." },
        { n: "03", t: "Yükü Uygula",          d: "Konteyner ortalama yüküyle çarp (ISO standardı)." },
        { n: "04", t: "Topla ve Raporla",     d: "Tüm ayaklar boyunca WTW (kuyudan tekere) emisyonlarını birleştir." },
      ],
      formulaEyebrow: "Formül", formulaTitle: "Segment başına temel hesaplama",
      efEyebrow: "Emisyon Faktörleri", efTitle: "Taşıma moduna göre",
      efSub: "g CO₂e / tonne-kilometre · WTW bazında",
      efNotes: {
        sea:     "En düşük yoğunluk; uzun mesafeli toplu yük için idealdir.",
        rail:    "Elektrikli çekiş; iç hat için düşük karbonlu seçenek.",
        railBRI: "Daha yüksek EF — dizel traksiyon + ray genişliği değişimleri.",
        roro:    "Roll-on/roll-off · orta yoğunluk.",
        road:    "En yüksek yoğunluk; kapıdan kapıya esneklik.",
      },
      contEyebrow: "Konteyner Yükleri", contTitle: "Ortalama kargo ağırlığı",
      contSub: "ISO konteyner özellikleri · operasyonel aralığın orta noktası",
      exEyebrow: "Örnek Hesaplama", exTitle: "Shanghai → ESBAŞ, Süveyş · 40FT",
      exSub: "Bu panodaki her sayı böyle işlemlerden oluşmaktadır",
      preCarriage: "Ön Taşıma", mainTransport: "Ana Taşıma", onCarriage: "Son Taşıma",
      totalCO2: "TOPLAM CO₂e",
      wtwEyebrow: "WTW ve TTW", wtwTitle: "Neden kuyudan tekere önemlidir",
      ttwTitle: "Tanktan Tekere (TTW)",
      ttwDesc:  "Yalnızca egzoz emisyonları — taşıma sırasında egzozdan çıkanlar.",
      ttwCov:   "Kapsam: yalnızca yanma",
      wtwTitle2: "Kuyudan Tekere (WTW)",
      wtwDesc2: "Tam yaşam döngüsü: yakıt çıkarma, rafinasyon, dağıtım VE yanma. TTW'den her zaman %20–30 daha yüksektir.",
      wtwCov2:  "Kapsam: kaynak + egzoz",
      wtwArrow: "→ kapsama alır →",
      stdEyebrow: "Standartlar ve Kaynaklar", stdTitle: "Bu sayılara neden güvenebilirsiniz",
    },
    footer: {
      dataset: "Veri Seti",      datasetVal: "4 kategori · deniz + kara + demiryolu",
      emission: "Emisyon Modeli", emissionVal: "EcoTransit WTW · ISO 14083 uyumlu",
      carto: "Kartografi",        cartoVal: "OpenStreetMap · CARTO temel haritası",
      copy: "© 2026 Eldor Trade Lanes — Akademik Yapı",
    },
    routeLabels: {
      "cn_suez_aliaga":    "Süveyş ile Deniz → Aliağa",
      "cn_cape_aliaga":    "Ümit Burnu ile Deniz → Aliağa",
      "cn_cape_alsancak":  "Ümit Burnu ile Deniz → Alsancak",
      "cn_bri":            "Orta Koridor Demiryolu (BTK)",
      "it_roro_truck":     "RoRo + Kamyon (Trieste)",
      "it_sea_truck":      "Deniz + Kamyon (Cenova)",
      "it_sea_rail":       "Deniz + Demiryolu (Trieste)",
      "it_roro_rail_truck":"RoRo + Demiryolu + Kamyon (Trieste)",
      "de_truck":          "Kamyon (Balkan Koridoru)",
      "de_roro_rail":      "RoRo + Demiryolu (Trieste)",
      "de_roro_truck":     "RoRo + Kamyon (Trieste)",
      "de_sea":            "Deniz (Akdeniz → Atlantik → Hamburg)",
      "it_imp_truck":      "Kamyon (Balkan Koridoru)",
      "it_imp_sea":        "Direkt Deniz (Akdeniz)",
      "it_imp_roro":       "Kamyon + RoRo (Trieste)",
    },
    routeDescs: {
      "cn_suez_aliaga":    "Jiangsu → Shanghai (en yakın liman), Süveyş Kanalı üzerinden Aliağa.",
      "cn_cape_aliaga":    "Jiangsu → Shanghai (en yakın liman), Ümit Burnu üzerinden Aliağa.",
      "cn_cape_alsancak":  "Jiangsu → Shanghai (en yakın liman), Ümit Burnu üzerinden Alsancak.",
      "cn_bri":            "Jiangsu → Xi'an kara yolu, Trans-Hazar demiryolu + BTK, ardından kamyon ile ESBAŞ.",
      "it_roro_truck":     "Çeşme → Trieste feribotu, A4 kamyon ile Milano.",
      "it_sea_truck":      "Konteyner gemisi Cenova'ya, A7 ile Milano.",
      "it_sea_rail":       "Gemi Trieste'ye, RFI blok treni ile Milano.",
      "it_roro_rail_truck":"Feribot Trieste'ye, demiryolu Bologna'ya, kamyon Milano'ya.",
      "de_truck":          "Kapıdan kapıya kara yolu (uzun mesafe).",
      "de_roro_rail":      "Feribot Trieste'ye, Tauern demiryolu ile Münih.",
      "de_roro_truck":     "Feribot Trieste'ye, A23 kamyon ile Avusturya üzerinden.",
      "de_sea":            "Cebelitarık'tan Hamburg'a, kamyon ile Frankfurt.",
      "it_imp_truck":      "Milano → İzmir kara yolu.",
      "it_imp_sea":        "Konteyner gemisi Cenova → Aliağa.",
      "it_imp_roro":       "Kamyon Milano → Trieste, RoRo Çeşme'ye.",
    },
  },
};
